import pygame, sys
from pygame.locals import *

CINZABORDA = (105,105,105)
CINZACHAO = (211,211,211)
CINZABLOCOFIXO = (169,169,169)
BLUE = (0,0,255)

BORDA=0
CHAO=1
BLOCOFIXO=2
COAL=3

colours = 	{
				BORDA : CINZABORDA,
				CHAO : CINZACHAO,
				BLOCOFIXO : CINZABLOCOFIXO,
				COAL : CINZABORDA
			}

tilemap= 	[
				[BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA],
				[BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				[BORDA,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BORDA],
				[BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				[BORDA,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BORDA],
				[BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				[BORDA,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BORDA],
				[BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				[BORDA,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BORDA],
				# [BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				# [BORDA,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BORDA],
				# [BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				# [BORDA,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BORDA],
				# [BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				# [BORDA,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BORDA],
				# [BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				# [BORDA,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BLOCOFIXO,CHAO,BORDA],
				[BORDA,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,CHAO,BORDA],
				[BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA,BORDA]
			]

TILESIZE=50
MAPWIDTH=15
MAPHEIGHT=11

pygame.init()
DISPLAYSURF = pygame.display.set_mode((MAPWIDTH*TILESIZE,MAPHEIGHT*TILESIZE))

while True:

	for event in pygame.event.get():
		if event.type == QUIT:
			pygame.quit()
			sys.quit()

	for row in range(MAPHEIGHT):
		for column in range(MAPWIDTH):
			pygame.draw.rect(DISPLAYSURF, colours[tilemap[row][column]], (column*TILESIZE, row*TILESIZE,TILESIZE,TILESIZE))

	pygame.display.update()